version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=StrongPassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

volumes:
  oracle-data:
